from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division


class KnowHowError(Exception):
    """
    Base exception class for all exceptions generated by knowhow itself.
    """


class ConfigError(KnowHowError):
    """
    Configuration errors.
    """
