language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"

# command to install dependencies
install:
  - pip install -r requirements.txt -r requirements.test.txt -c constraints.txt
  - pip install -e .

# command to run tests
script: pytest
branches:
  only:
    - master
